### PR TITLE
A lot of commits

### PR DESCRIPTION
**Pull request by AlessandroMIlani**
Ok, small recap on the changes

The two main added features are:
- username and password different for each container
- different incus network for each container

Besides those, other minor changes are:
- save one config.sh for each container (with the updated user and password) in .config/inculs-manager
- added a base input check for incul-manager actions
- added a GPL-3.0 license
- delete config.sh from containers File System at the end of the configuration (To avoid having a file with plain-text data)
- updated install instruction (but I'm thinking to implement a one line installer, automatic download and execution of a script, to also remove the inlcus-manager init action)

### CODE REVIEW

**Comment by AlessandroMIlani** [comment]
@munabedan there are some problems with the request? 
I took a look to the GitGuardian Security Check, and it has been triggered by your hard definition of the container's passwords in `etc/inculs-manager/config.sh`. I think it can be ignored without any problem, because now is asked directly to the user

**Comment by munabedan** [comment]
Yes, I noticed that. Shouldn't really be a problem. I am currently checking out your commits.

**Comment by AlessandroMIlani** [comment]
If the number and quality of commits may bother you, I may cancel this pull request and open a more concise one (now that I know what and how to do, I may reduce them by a lot).

Surely the next ones will be better organized

**Review by munabedan — APPROVED** [review]

**Review by munabedan — APPROVED** [review]

**Review by munabedan — APPROVED** [review]

**Review by munabedan — APPROVED** [review]

**Comment by munabedan** [comment]
> If the number and quality of commits may bother you, I may cancel this pull request and open a more concise one (now that I know what and how to do, I may reduce them by a lot).
> 
> Surely the next ones will be better organized

I think this might actually be the way to go. It is taking too long for me to review each commit. I don't currently have any standards laid out for pull requests but here are two things to consider for quick merges. 
1.  Each commit must not break the Debian build. Meaning each commit change can be compiled into a Debian package without errors. This will make it easier for me to test each commit point.
2. Each commit should contain logically related changes that roll up to a feature that can be easily understood. This will prevent having too many commits in on PR. I believe utilizing Git squash features might help you coalesce commits that implement one specific feature. A good starting point would be to split the username and password, and the new network implementation into two specific commits.

**Comment by munabedan** [comment]
> If the number and quality of commits may bother you, I may cancel this pull request and open a more concise one (now that I know what and how to do, I may reduce them by a lot).
> 
> Surely the next ones will be better organized

I think this might actually be the way to go. It is taking too long for me to review each commit. I don't currently have any standards laid out for pull requests but here are two things to consider for quick merges. 
1.  Each commit must not break the Debian build. Meaning each commit change can be compiled into a Debian package without errors. This will make it easier for me to test each commit point.
2. Each commit should contain logically related changes that roll up to a feature that can be easily understood. This will prevent having too many commits in on PR. I believe utilizing Git squash features might help you coalesce commits that implement one specific feature. A good starting point would be to split the username and password, and the new network implementation into two specific commits.

With that I think I can safely close this one and wait for the one you open a new PR.

**Pull request closed without merging**
