### PR TITLE
Custom user and password for each container 

### PR DESCRIPTION
**Pull request by AlessandroMIlani**
I've decided to keep the default "incul" user for the template and implement the custom user only within the user's containers.

To make this work, when a new container is created, the `create` function generates a copy of the config.sh file in the `$HOME/.config/incul-manager` folder, with the updated value for user and password.
For this reason, also config_file in `usr/bin/incul-sync` is changed, with a fallback for containers (template) that not have their own configuration file.

NOTE: About  `sync,` at the moment for the templates I've insert the fallback to config.sh for avoid broken .desktop file, but if the idea is to keep them only as a base for avoid to recreate a full container each time, an idea could be complete remove the access to them from the desktop environment (so from xfce4 panel the user can access only to container create with the command `incul-manager create <container-name>`

### CODE REVIEW

**Comment by munabedan** [comment]
>NOTE: About sync, at the moment for the templates I've insert the fallback to config.sh for avoid broken .desktop file, but if the idea is to keep them only as a base for avoid to recreate a full container each time, an idea could be complete remove the access to them from the desktop environment (so from xfce4 panel the user can access only to container create with the command incul-manager create <container-name>

My thoughts on this was a function similar to Qubes OS where the user is able to create different templates for different purposes.

**Comment by munabedan** [comment]
Screenshot at 2024-11-14 19-34-11

I think we should wipe the config file after the container is created, especially since it contains the password and username.

**Comment by AlessandroMIlani** [comment]
> Screenshot at 2024-11-14 19-34-11
> 
> I think we should wipe the config file after the container is created, especially since it contains the password and username.

Yes, but we need them. Because each time the user use the sync function, to create the .desktop files, are need user and password to complete the xpra command in the exec section.

`new_exec="Exec=bash -c 'xpra start ssh://$username:$password@$container_ip --title=\"${container_name^}: @title@\" --border=${colors[$index]},3 --exit-with-children --start-child=\"$old_args\"'"`

An alternative, could be use always the username of the host user (so only custom password ) and than ask the password each time a program is opened from the xfce panel

**Comment by AlessandroMIlani** [comment]
To be complete, also each` .desktop` file in `folder_path="/home/$USER/.local/share/applications/$container_name"` have user and password hard-coded. 

At the moment, the only option I can think of to avoid a hard-coded password is the use of the same username as the host (as said before). In this way, if we write the ssh command as `ssh $container_ip ...` it automatically use the name of the user as parameter and only ask for a password.

Or, probably more complex, at the creation of the container, we need to also create an ssh key pair and use them for the connection

**Comment by AlessandroMIlani** [comment]
Ok, I've find a way to use ssh key for access containers, in this way, we can keep the  config file with only the username info (and it remains available in case we later need to pass more data).

I now close this commit and, time to clean up some code, reopen another one with ssh keys enabled

**Pull request closed without merging**
